# This is a workflow to create json from opendata(csv) and deploy with Actions

name: feed-to-json and deploy
env:
  TZ: Asia/Tokyo
on:
  schedule:
    - cron:  '00 */1 * * *'
  workflow_dispatch:
jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: production

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: pip install feedparser
      - name: Run python script (feedreader.py)
        run: python3 -B production/tools/feedreader.py > production/data/feed.json

      - name: Create Pull Request main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: production
          commit-message: BOT; UPDATE DATA
          title: BOT; UPDATE DATA to main
          base: main
          branch: data-bot/main
          labels: auto_merge
