# This is a workflow to create image data from html and deploy with Actions

name: html-to-image and deploy
env:
  TZ: Asia/Tokyo
on:
  schedule:
    - cron:  '05 */3 * * *'
  workflow_dispatch:
jobs:
  create_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: production

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      
      - name: Install yarn
        run: yarn install
      - name: Install dependencies
        run: yarn install puppeteer
      - name: Run js script (app.js)
        run: node production/puppeteer-app/app.js

      - name: Create Pull Request main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: production
          commit-message: BOT; UPDATE IMAGE
          title: BOT; UPDATE IMAGE to main
          base: main
          branch: data-bot/main
          labels: auto_merge
